apiVersion: v2
name: crm-saas
description: A comprehensive CRM SaaS application
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - crm
  - saas
  - react
  - nodejs
  - mongodb
home: https://github.com/your-username/crm-saas
sources:
  - https://github.com/your-username/crm-saas
maintainers:
  - name: Your Name
    email: your.email@example.com
dependencies:
  - name: mongodb
    version: "~13.0.0"
    repository: "https://charts.bitnami.com/bitnami"
    condition: mongodb.enabled
